name = "gb-issue-assigner-agent"
main = "src/index.ts"
compatibility_date = "2023-05-15"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for storing stats and metadata (if needed)
# kv_namespaces = [
#   { binding = "ISSUE_STATS", id = "demo", preview_id = "demo" }
# ]

# Durable Object for the AI Agent
[[durable_objects.bindings]]
binding = "GitHubIssueAssignerAgent"
class_name = "GitHubIssueAssignerAgent"

# Required for Durable Objects to store state
[[migrations]]
tag = "v1"
new_sqlite_classes = ["GitHubIssueAssignerAgent"]

# AI bindings
[ai]
binding = "AI"

# Environment variables - replace with actual values in production
[vars]
GITHUB_TOKEN = "replace-with-actual-token"
GITHUB_REPO_OWNER = "your-org-or-username"
GITHUB_REPO_NAME = "your-repo-name"

# Add AWS credentials for future enhancements
# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
# AWS_REGION = "us-east-1"
